# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
 vesel_repository:
  class: AppBundle\Repository\VeselRouteRepository
  factory: ["@doctrine","getRepository"]
  arguments: ["AppBundle:VesselMoveStatus"]

 app.exception_listener:
  class: AppBundle\EventListener\ExceptionListener
  arguments: ["%kernel.environment%"]
  tags:
   - { name: kernel.event_listener, event: kernel.exception }
   
 app.request_subscriber:
    class: AppBundle\EventSubscriber\BeforeResolvingController
    arguments: ["%kernel.environment%"]
    tags:
      - { name: kernel.event_subscriber }